@OPWebApp.Server_HostAddress = http://localhost:5267


GET {{OPWebApp.Server_HostAddress}}/api/players

###

POST {{OPWebApp.Server_HostAddress}}/api/players
Content-Type: application/json

{
  "name": "XTerminator",
  "level": 5,
  "xp": 2693,
  "description": "Destroy all humans!"
}

###

POST {{OPWebApp.Server_HostAddress}}/api/players
Content-Type: application/json

{
  "name": "Gordon",
  "level": 45,
  "xp": 2699878,
  "description": "Orange is my favourite color!"
}

###

GET {{OPWebApp.Server_HostAddress}}/api/players/482cf139-1cdb-4747-bfa2-84e51621e92b

###

PUT {{OPWebApp.Server_HostAddress}}/api/players/{482cf139-1cdb-4747-bfa2-84e51621e92b}
Content-Type: application/json

{
  "id": "482cf139-1cdb-4747-bfa2-84e51621e92b",
  "name": "XTerminator",
  "level": 6,
  "xp": 789254,
  "description": "Destroy all humans again!!"
}

###

POST {{OPWebApp.Server_HostAddress}}/api/players
Content-Type: application/json

{
  "name": "tester",
  "description": "Something"
}

###

PATCH {{OPWebApp.Server_HostAddress}}/api/players/{5779d7bf-d6c2-4a8b-aa68-a13c49f54693}/xp
Content-Type: application/json
{
  "xp": 789254
}

###
